---

- name: create content view task file directory
  file:
    path: "{{ generated_files_path }}/content-views"
    state: directory
  delegate_to: "{{ delegate_host }}"

- name: push task file to create content view based on number of repos
  template:
    src: templates/content-view.yml.j2
    dest: "{{ generated_files_path }}/content-views/{{ content_view.name }}.yml"
  loop_control:
    loop_var: content_view
  loop: "{{ organization.content_views }}"
  delegate_to: "{{ delegate_host }}"

- name: include tasks to create content views
  include_tasks: "{{ generated_files_path }}/content-views/{{ content_view.name }}.yml"
  loop_control:
    loop_var: content_view
  loop: "{{ organization.content_views }}"
