---

- name: run from {{ delegate_host }}
  block:
    - name: get all respositories to sync
      redhat.satellite.resource_info:
        username: "{{ satellite.admin_username }}"
        password: "{{ satellite.admin_password }}"
        validate_certs: false
        server_url: "{{ satellite_url }}"
        resource: repositories
        organization: "{{ organization.organization_name }}"
      register: repositories
    
    - name: trigger repository syncs
      redhat.satellite.repository_sync:
        username: "{{ satellite.admin_username }}"
        password: "{{ satellite.admin_password }}"
        validate_certs: false
        server_url: "{{ satellite_url }}"
        organization: "{{ organization.organization_name }}"
        repository: "{{ repository.name }}"
        product: "{{ repository.product.name }}"
      async: 86400
      poll: 0
      loop: "{{ repositories.resources }}"
      loop_control:
          loop_var: repository

    - name: wait for respository syncs to start
      ansible.builtin.pause:
        seconds: 30
    
    - name: wait for repository syncs to finish
      redhat.satellite.resource_info:
        username: "{{ satellite.admin_username }}"
        password: "{{ satellite.admin_password }}"
        validate_certs: false
        server_url: "{{ satellite_url }}"
        resource: foreman_tasks
        search: action ~ Synchronize repository and state != stopped
      register: respository_sync_tasks
      until: respository_sync_tasks.resources | length == 0
      retries: 2880
      delay: 30
  delegate_to: "{{ delegate_host }}"
