namespace: jjaswanson4
name: configure_satellite
version: 2.1.0
readme: README.md
authors:
authors:
- Josh Swanson <jswanson@redhat.com>
- Scott Danielson <sdaniels@redhat.com>
- Rodrique Heron <rheron@redhat.com>
- Derek Winters <contact@derekwinters.com>
description: This collection configures a satellite 6 server
license:
- GPL-2.0-or-later
tags:
  - satellite6
  - configure_satellite
  - rhel7
#dependencies:
#  "jjaswanson4.install_satellite": "*"
repository: https://github.com/jjaswanson4/configure_satellite
documentation: https://github.com/jjaswanson4/configure_satellite/blob/master/README.md
homepage: https://github.com/jjaswanson4/configure_satellite
issues: https://github.com/jjaswanson4/configure_satellite/issues
