---

- name: configure repos for custom products
  theforeman.foreman.repository:
    username: "{{ satellite.admin_username }}"
    password: "{{ satellite.admin_password }}"
    validate_certs: "{{ repo.1.validate_certs | default(false) }}"
    server_url: "{{ satellite_url }}"
    organization: "{{ organization.organization_name }}"
    state: "{{ repo.1.state | default('present') }}"
    content_type: "{{ repo.1.content_type | default('yum') }}"
    name: "{{ repo.1.repo }}"
    product: "{{ repo.1.product }}"
    url: "{{ repo.1.repo_url }}"
    mirror_on_sync: "{{ repo.1.mirror_on_sync | default(false) }}"
    download_policy: "{{ repo.1.download_policy | default('immediate') }}"
    gpg_key: "{{ repo.1.content_credential_name | default(omit) }}"
    checksum_type: "{{ repo.1.checksum_type | default(omit) }}"
    unprotected: "{{ repo.1.unprotected | default(omit) }}"
    upstream_username: "{{ repo.1.upstream_username | default(omit) }}"
    upstream_password: "{{ repo.1.upstream_password | default(omit) }}"
  when:
    - repo.1.repo is defined
    - repo.1.product is defined
    - repo.1.repo_url is defined
    - repo.1.custom_repo is defined
  loop_control:
    loop_var: repo
  loop: "{{ organization.content_views | subelements('repos') }}"
  delegate_to: "{{ delegate_host }}" 
